name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I have also considered...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature primarily affect?
      options:
        - API Compatibility
        - Model Management
        - Performance/GPU
        - Monitoring/Dashboard
        - Configuration
        - Documentation
        - Deployment
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Blocking my use case
        - Critical - Required for production

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help.
      placeholder: I need this feature because...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how the feature would work (API calls, config, etc.)
      render: bash

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing the implementation
        - label: I can help with documentation

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for this feature
          required: true
        - label: This feature is not already available in the current version
          required: true
        - label: This feature would benefit other users, not just my specific case
          required: true